import { useId, type ReactElement, type ReactNode } from 'react'
import FormControl from '@mui/material/FormControl'
import FormControlLabel from '@mui/material/FormControlLabel'
import FormHelperText from '@mui/material/FormHelperText'
import FormLabel from '@mui/material/FormLabel'
import { useDefaultProps } from '@mui/material/DefaultPropsProvider'
import { useEzField, type InputA11y, type NameA11y } from '../useEzField'
import type { TypedControllerRenderProps } from '../useEzField'
import type { LabelPlacement } from '../LabelPlacementContext'
import { mergeDisabled } from '../mergeDisabled'
import type { FieldRules } from '../../rules'
import { hasLabel } from '../../devWarn'

/**
 * What `<BoundField>` hands its `render` prop: everything the binding knows about
 * this field, for a control it renders itself. The control composes its own
 * handlers after `field.onChange`.
 *
 * Generic over the field's `TValue`, so `field.value` is the field's value type
 * (`boolean` for Checkbox, `Value[]` for CheckboxGroup, a consumer's own shape for
 * a wrapped control) rather than `any`, and `field.onChange` rejects a value of the
 * wrong shape (#28).
 *
 * ### Two members are not optional for the control to be usable
 *
 * `field.ref` and `inputA11y` must both reach the element that carries the role:
 *
 * - **`field.ref`** is what hookform focuses after a failed submit, and — through
 *   the fork in `useEzField` — what registers this field's focus target so
 *   `<FormErrorSummary>` can link to it (#98). A control that drops it renders an
 *   error the user is never taken to.
 * - **`inputA11y`** carries `aria-invalid` and the **merged** `aria-describedby`
 *   (the consumer's own ids joined with the helper text's, #102/#104). A control
 *   that drops it shows an error message no screen reader ever associates with it.
 *
 * `nameA11y` is the third, for a field with no visible `label`: put it on the same
 * element. Left to a wrapper it names the `FormControl` `<div>`, which leaves the
 * real control anonymous while axe reports clean (#99) — the exact failure that
 * shipped across 15 of 17 fields.
 */
export interface Bound<TValue = unknown> {
  field: TypedControllerRenderProps<TValue>
  invalid: boolean
  required: boolean
  /** Resolved against the helper text: `aria-describedby` is set only when there is text. */
  inputA11y: InputA11y
  /**
   * The consumer's `aria-label` / `aria-labelledby`, for the element that carries
   * the role. A key the consumer did not pass is **absent**, not `undefined`, so
   * spreading this cannot erase an `aria-labelledby` the control set for itself.
   *
   * The seven fields inside this library route these through their own `{...rest}`
   * instead, because they have one; a `render` prop has no `rest`, so this is the
   * only channel (#99).
   */
  nameA11y: NameA11y
  /**
   * Id of the label element — the legend when `labelAs="legend"`, or the one the
   * consumer renders under `labelAs="none"`. Put it in `aria-labelledby` on the
   * element carrying the role.
   *
   * `undefined` when there is no label to render, so the attribute is dropped rather
   * than pointing at an empty legend. That matters because `aria-labelledby` outranks
   * `aria-label` in the accname algorithm: an id resolving to `""` does not fall back
   * to `aria-label`, it leaves the control with no accessible name at all (#100).
   */
  labelId: string | undefined
  /**
   * Id for the control itself, so a `labelAs="none"` consumer can pair their own
   * `<label htmlFor={bound.controlId}>` with `id={bound.controlId}`.
   *
   * Generated by the frame rather than left to the consumer so `labelId` and
   * `controlId` are always a matched pair from one `useId` call — a consumer
   * supplying one and forgetting the other is the mismatch this removes.
   */
  controlId: string
  /**
   * The label to render: the `label` prop unchanged in `asterisk` mode; in
   * `optional` mode an optional field's label carries the form's `optionalText`
   * (#66). Only `labelAs="none"` needs it — the other two modes render it already.
   */
  displayLabel: ReactNode
  /**
   * `false` in `optional` mode when the field is required (so a label element renders
   * no asterisk while the control keeps `required`/`aria-required`); `undefined`
   * otherwise, so a MUI label picks up `FormControl`'s own `required`.
   */
  labelRequired: false | undefined
  /**
   * The text shown under the control: the error message when there is one, else the
   * consumer's `helperText`. Already rendered by the frame in every mode — exposed so
   * a control with a description slot of its own can show the same text.
   */
  helperText: ReactNode
  /**
   * Id of the rendered helper text. Already in `inputA11y['aria-describedby']`;
   * exposed for a control that needs to point at it from somewhere else.
   */
  helperTextId: string
}

/**
 * Where the label markup comes from.
 *
 * - `'none'` (the default): the frame renders **no label element**. It hands back
 *   `displayLabel`, `labelId`, `controlId` and `labelRequired` for the consumer to
 *   place, and renders only the `FormControl` box and the helper text. The right
 *   mode for any control that owns its own label — which is most of them, and why
 *   it is the default: a control the frame knows nothing about is one it cannot
 *   choose label markup for.
 * - `'control'`: label beside the control (MUI `FormControlLabel`, a `<label>`
 *   wrapping it) — Checkbox, Switch.
 * - `'legend'`: label above a group of controls (`<fieldset>` + `<legend>`) —
 *   RadioGroup, Rating, Slider, CheckboxGroup, ToggleButtonGroup. A `legend` frame
 *   renders a fieldset whose implicit role is `group` named by the legend; when the
 *   inner control is itself `role="group"`, it shares that same accessible name, so
 *   tests must disambiguate by picking the inner element rather than querying by the
 *   shared name alone.
 */
export type BoundFieldLabelAs = 'none' | 'control' | 'legend'

export interface BoundFieldProps<TValue> {
  name: string
  /**
   * The name this field is called in the "must be rendered inside `<Form>`" error and
   * in the dev-mode warnings. Defaults to `'BoundField'`; set it to your own component's
   * name so those messages name something the consumer can find.
   */
  componentName?: string
  label?: ReactNode
  helperText?: ReactNode
  disabled?: boolean
  rules?: FieldRules<TValue>
  /** Which label markup the frame renders; `'none'` by default. See `BoundFieldLabelAs`. */
  labelAs?: BoundFieldLabelAs
  /**
   * The consumer's ARIA name for a field with no visible `label`.
   *
   * Reported here so the dev-mode "no accessible name" warning can see that a
   * label-less field is named some other way (see `src/devWarn.ts`), *and* handed
   * back on `bound.nameA11y` for `render` to put on the element that carries the
   * role. Both halves matter: a name left on the wrapper names a `<div>` (#99).
   *
   * This used to say a `labelAs="legend"` field must *not* report them, on the
   * reasoning that its `aria-labelledby={labelId}` is set after `rest` and so wins
   * anyway. That was the bug (#100) written down as intent: the frame emitted
   * `aria-labelledby` even with no legend content, and an `aria-labelledby` naming an
   * empty element beats `aria-label` in the accname algorithm — so those fields ended
   * up with **no** accessible name while the warning that would have said so was
   * suppressed. `labelId` is now `undefined` without a label, which leaves a
   * consumer's `aria-label` as the name, exactly as plain MUI does.
   */
  'aria-label'?: string
  'aria-labelledby'?: string
  /**
   * The consumer's own `aria-describedby`, merged with the helper text's id into
   * `bound.inputA11y` rather than replaced by it (#102 row 8, the family-wide half
   * of #104).
   *
   * Each of the seven fields inside this library also passes it through `{...rest}`,
   * where it reaches MUI's root and describes the `FormControl` **wrapper** — a
   * `<div>` no assistive tech reads. `bound.inputA11y` is applied to the real control
   * after that, so the merged value wins there and the wrapper copy is inert. Measured
   * before the fix: with `aria-describedby="mine"`, every one of Checkbox, Switch,
   * RadioGroup, Rating, Slider, CheckboxGroup and ToggleButtonGroup put only the
   * helper-text id on the control — the consumer's description never arrived at all,
   * before *or* after a failed submit.
   */
  'aria-describedby'?: string
  /** This field's own label placement, overriding the form's (#9, #66). */
  labelPlacement?: LabelPlacement
  /** The consumer's `className`, appended after the placement classes. */
  className?: string
  /**
   * Renders the control, given everything the binding knows about the field.
   *
   * The returned element **must** carry `bound.field.ref` and `bound.inputA11y` on
   * whichever element holds the role, and `bound.nameA11y` too when the field has no
   * visible `label` — see `Bound` for what each one costs if it is dropped.
   */
  render: (bound: Bound<TValue>) => ReactElement
}

/**
 * Binds one field to the enclosing `<Form>` and hands a `render` prop everything the
 * binding knows: the typed `field`, the a11y attributes, the label and helper text.
 * It renders the `FormControl` box, the helper text, and — under `labelAs` — the
 * label; the control itself is entirely the caller's.
 *
 * This is both the library's own frame for the seven fields that are not a MUI
 * `TextField` (Checkbox, Switch, RadioGroup, Rating, Slider, CheckboxGroup,
 * ToggleButtonGroup) and the public way to bind a control this library does not
 * wrap. One component, deliberately: the four things a consumer cannot get right
 * unaided — the `field.ref` fork that registers the focus target (#98), the
 * `aria-describedby` merge (#102/#104), the empty-`aria-labelledby` trap (#100) and
 * the `aria-label` routing (#99) — were all this library's own bugs, and a second
 * parallel binding path would be a second place for each of them to come back.
 */
export function BoundField<TValue>(inProps: BoundFieldProps<TValue>) {
  const {
    componentName = 'BoundField',
    name,
    label,
    helperText,
    disabled,
    rules,
    labelAs = 'none',
    'aria-label': ariaLabel,
    'aria-labelledby': ariaLabelledBy,
    'aria-describedby': ariaDescribedBy,
    labelPlacement,
    className,
    render,
  } = useDefaultProps({ props: inProps, name: 'EzBoundField' })
  const f = useEzField<TValue>(name, componentName, {
    label,
    rules,
    'aria-label': ariaLabel,
    'aria-labelledby': ariaLabelledBy,
    labelPlacement,
    className,
  })
  // One call, two ids: `labelId` and `controlId` are always a matched pair, which is
  // what a `labelAs="none"` consumer pairs `<label htmlFor>` with `id`.
  const ids = useId()
  const labelId = `${ids}-label`
  const controlId = `${ids}-control`
  const text = f.helperText(helperText)
  // `label`, not `displayLabel`: in `optional` mode `displayLabel` wraps a missing label
  // with the "(optional)" suffix, which is not a name — a legend reading "(optional)"
  // alone would be worse than none. Shared with `warnMissingLabel`, so the same input
  // that warns is exactly the input that gets no legend.
  const labelled = hasLabel(label)
  const bound: Bound<TValue> = {
    field: f.field,
    invalid: f.invalid,
    required: f.required,
    // `describedBy`, not `inputA11y`: an accessible description is a *list*, so the
    // consumer's ids and the helper text's are joined rather than one replacing the
    // other. `inputA11y` supplies `aria-invalid` unchanged (#102 row 8).
    inputA11y: {
      ...f.inputA11y(text),
      'aria-describedby': f.describedBy(ariaDescribedBy, text),
    },
    nameA11y: f.nameA11y,
    labelId: labelled ? labelId : undefined,
    controlId,
    displayLabel: f.displayLabel,
    labelRequired: f.labelRequired,
    helperText: text,
    helperTextId: f.helperTextId,
  }
  // FormControlLabel/FormLabel read `required` from FormControl context only when
  // their own prop is undefined; passing `f.labelRequired` (`false` in `optional`
  // mode for a required field) wins over that context and suppresses the asterisk
  // while FormControl's own `required` (and so the input's `aria-required`) is
  // untouched.
  const labelRequired = f.labelRequired ?? f.required

  return (
    <FormControl
      component={labelAs === 'legend' ? 'fieldset' : 'div'}
      className={f.layoutClassName}
      error={f.invalid}
      disabled={mergeDisabled(disabled, f.field.disabled)}
      required={f.required}
    >
      {labelAs === 'control' ? (
        <FormControlLabel
          label={f.displayLabel}
          required={labelRequired}
          control={render(bound)}
        />
      ) : labelAs === 'legend' ? (
        <>
          {/* No legend at all without a label: an empty one is markup nothing can use,
              and in `optional` mode `displayLabel` would render a bare "(optional)". */}
          {labelled ? (
            <FormLabel component="legend" id={bound.labelId} required={labelRequired}>
              {f.displayLabel}
            </FormLabel>
          ) : null}
          {render(bound)}
        </>
      ) : (
        // `none`: no label element at all. `displayLabel`, `labelId`, `controlId` and
        // `labelRequired` are on `bound` for the consumer to place, because a control
        // this frame knows nothing about is one it cannot choose label markup for.
        render(bound)
      )}
      {text ? <FormHelperText {...f.helperTextA11y}>{text}</FormHelperText> : null}
    </FormControl>
  )
}
